### ISSUE TITLE
解答の説明の書き方

### ISSUE THREAD

**Issue by fulfom** [fulfom/iolingjapan#41]
解答の説明の書き方が分かるような資料を作って公式サイトに公開する．

- 発見したパターンや規則は全て書く．構造と体系を意識せよ．
- エッセイではない．（どのデータを参照したか，は書くべきでなく，どういった規則が見つけられたかを書くべき．）
- 図や表を用いて良い．積極的に用いよ．
- 単語リストは原則不要．ただし，特徴的なもの，単語の「分類基準」は書く．e.g. 
- 自他の区別をせよ．構造をかき分けよ．

具体的な模範解答（数パターン）を用意して公開する．
模範じゃない解答もあった方が良い．

**Comment by fulfom** [comment]
次回の練習会までにこれは出す．何としても出す．

**Comment by fulfom** [comment]
アウトライン

## 解答の説明の配点

APLOやIOLで配点があるよ，全くないのもあるけど，あるやつは大抵約3〜6割が解答の説明に当てられるよ

IOLやAPLOの解答には説明が書いてあるけど，あれが実は解答の説明の模範解答にもなっているよ．つまりあんな解答の説明を書けば満点がくるよ．

**Comment by KumagaeYuki** [comment]
iol-bookにマージします．
